POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjQ2MTAwNDQsInVzZXJJZCI6MX0.G8UDzQ3nbFfWkwNcswgxHdDr7K_lwsuaG4iw7V3Zk88

{

    "name": "Test Event",
    "description": "A test event",
    "location": "A test location",
    "datetime": "2025-01-01T15:30:00.00Z"
}